### ISSUE TITLE
Database connection failed!

### ISSUE THREAD

**Issue by sadoj-kuro** [Jason2605/AdminPanel#11]
i have a Database connection failed!

but all information or connection its ok.

the panel create table in the DB and after created this say me this error :\

**Comment by Jason2605** [comment]
Alright, first thing i would like you to try is delete the file called verifyPanel.php and reset up your panel, if issues persist join the discord, https://discord.gg/kZCTRPk and ill help you from there.

**Comment by sadoj-kuro** [comment]
I already attemp  this  my  english  its  bad i ask to shakir for  talking
with  you

**Comment by Jason2605** [comment]
I haven't heard anything, is this still an issue?

**Comment by sadoj-kuro** [comment]
yes  actually the problem is same

**Comment by Jason2605** [comment]
Alright, join the discord link i sent you and ill be able to assist further from there.
