### ISSUE TITLE
Unable to connect to rcon 

### ISSUE THREAD

**Issue by KaydenD** [Jason2605/AdminPanel#12]
When I try to do any rcon related task on the panel it shows me this

````
Notice: Uninitialized string offset: -1 in D:\Xampp\htdocs\ArmaRConClass\rcon.php on line 117

Fatal error: Uncaught exception 'Nizarii\ArmaRConClass\AuthorizationException' with message '[ARC] Login failed, wrong password!' in D:\Xampp\htdocs\ArmaRConClass\rcon.php:118 Stack trace: #0 D:\Xampp\htdocs\ArmaRConClass\rcon.php(283): Nizarii\ArmaRConClass\ARC->authorize() #1 D:\Xampp\htdocs\ArmaRConClass\rcon.php(93): Nizarii\ArmaRConClass\ARC->connect() #2 D:\Xampp\htdocs\verifyPanel.php(20): Nizarii\ArmaRConClass\ARC->__construct('XXXXXXXXXXX', XXXX, 'XXXXXXXXXX...') #3 D:\Xampp\htdocs\rCon\rcon-mess.php(18): Rconconnect() #4 {main} thrown in D:\Xampp\htdocs\ArmaRConClass\rcon.php on line 118
```` 

I replaced all the IP, port and password with X's but believe me I copied that info into DART and it worked fine. I have tried running the web server on the box and from a remote computer. When it was on the box the rcon and DB host  was 127.0.0.1 and when it was remotely hosted web server I used the game server/Rcon/DB boxes IP both time I got the same error I posted. Rcon works anywhere else.

**Comment by Jason2605** [comment]
The Rcon is the server ip and the icon port specified in the BEServer.cfg. The error you are faced with is when the information inputted is not correct. Please check for any invalid input again at let me know how it goes.

**Comment by Jason2605** [comment]
Update for personal notes - some characters cause issues in the panel icon and in this case it was '!'. To fix just remove those types of characters, until a designed fix is brought out.
