### ISSUE TITLE
the API setting

### ISSUE THREAD

**Issue by JacobKabir** [Jason2605/AdminPanel#15]
Ok what does the Whitelist staff user do? is that like permission to have infistar in game?

**Comment by JacobKabir** [comment]
Never Mind i have fixed that problem but i just locked myself out of the panel how would i go about getting back in?

**Comment by JacobKabir** [comment]
Never mind i fixed that but what is wrong with the Rcon it wont send messages restart or stop the server do you have a clue what is wrong?

**Comment by Jason2605** [comment]
Whitelist staff user makes the user unable to be banned/kicked etc through the AdminPanel itself, nothing to do with infiSTAR.

**Comment by JacobKabir** [comment]
Oh ok also with the permissions how do i make it bc i want admins to have acces to the player area so they can whitelist but it also gives access to change the bank bc there are no logs for that

**Comment by Jason2605** [comment]
On the staff page, there is an "Edit" button, in there, there are many different permissions you can add/take away from staff users to control their actions. **Sorry for the late reply.**

**Comment by Jason2605** [comment]
Im taking no reply as there is no longer an issue, if there is just reopen it.
