### ISSUE TITLE
Error - verifyPanel.php

### ISSUE THREAD

**Issue by RespawnGaming** [Jason2605/AdminPanel#16]
Not changed anything. uploaded and entered my info and now im getting this error

Parse error: syntax error, unexpected 'default' (T_DEFAULT) in /home/agcncouk/public_html/mystats/verifyPanel.php on line 49

**Comment by Jason2605** [comment]
This was due to an issue with the API, there was a fix pushed yesterday however the release wasn't updated, should be now. Just swap your files out and reinstall.

**Comment by Jason2605** [comment]
Im taking no reply as there is no longer an issue, if there is just reopen it.
