### ISSUE TITLE
Rcon issues

### ISSUE THREAD

**Issue by UltimaA380** [Jason2605/AdminPanel#26]
I cannot restart the server or send a message or anything. Other RCon clients work flawless.

**Comment by Jason2605** [comment]
Are you still having issues? Sorry it took as long to respond.

**Comment by UltimaA380** [comment]
Yes it still has the same problem :/

**Comment by majoess** [comment]
php Logs?

**Comment by Jason2605** [comment]
Guessing this has went stale, any further issues just reopen and we will go from there.

**Comment by UltimaA380** [comment]
I'm currently on vacation, sorry for not responding. But when I left I
still had the issue, will resume when I'm off.

**Comment by Jason2605** [comment]
No issue at all, just reopen here or on discord when you're back if you still can't get it to work.
