### ISSUE TITLE
I am unable to create and database, the only page I can access is create.php

### ISSUE THREAD

**Issue by Hectrim** [Jason2605/AdminPanel#29]
Title says it all. When I am on create.php, how do I actually create the server? Im a sort of a noob when it comes to installing this - How do I install this?! Thanks

**Comment by Hectrim** [comment]
Another issue is that I cant sign in. And how do I actually link this to a database?

**Comment by Jason2605** [comment]
Hi Hectrim,

The issue you are experiencing to me sounds as though the file verifyPanel.php is not being wrote upon creation of the panel. You link this to your database via the create page which you say you are being linked too. If you are using a linux web host you will need to grant the panel access to write files, however once done you should revoke that.

**Comment by Jason2605** [comment]
6 days no response, reopen if you are still having issues.
