### ISSUE TITLE
RCON doesn't work

### ISSUE THREAD

**Issue by iteamvep** [Jason2605/AdminPanel#30]
"The RCON doesn't work, just shows a blank page and doesn't do anything." —— From Strobe，altisliferpg.com

**Comment by iteamvep** [comment]
I have the same problem.Does bis change the api?

**Comment by Jason2605** [comment]
If you are getting a blank page via RCON commands, your RCON is not set up correctly for the panel, nothing to do with bohemia

**Comment by iteamvep** [comment]
Ok,and...when I tried to update the settings,updateSettings.php echo "error?1". what's that means?

**Comment by Jason2605** [comment]
If you join the discord ill be able to assist better there, link is on the homepage of the repo

**Comment by iteamvep** [comment]
Ok.
