### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Dym1161** [Jason2605/AdminPanel#33]
Hello, Hello, I have a problem with your admin panel I explain:

When I put the information from the DB, at the end it writes me "connection failed". Knowing that I am French, is it possible to help me, please, thank's you

**Comment by Jason2605** [comment]
Hello,

If you are getting connection failed there could be a few things you will need to check, however that connection is on about the connection to your database. So, please check that the database server is accessible from wherever the panel is being posted. This may mean checking ports are opened, checking the user you are trying to use has the correct permissions to be able to get accessed from that particular IP address. And most obviously, check that your details are actually correct. Let me know how it goes.

**Comment by Jason2605** [comment]
No comment after 20 days
