### ISSUE TITLE
Panel in subdirectory

### ISSUE THREAD

**Issue by Finch-Tamo** [Jason2605/AdminPanel#7]
Hi, your panel is great but when i put it in a subdirectory, some redirection was wrong... 
Exemple : When i want sen a Rcon message, i go from " http://xxxxx/admin/home.php " to " http://xxxxx/home.php " 

Thx for your work ;)

**Comment by Jason2605** [comment]
There was a new update released fixing that about 2 hours ago, re-downlaod. Thanks for the kind words too.

**Comment by Finch-Tamo** [comment]
Sorry but it's not working find :s he return a 404 not found beacause he search on root ...

**Comment by Jason2605** [comment]
Ive just downloaded the newest version and it works fine for me.

**Comment by Finch29** [comment]
me too but : http://i.imgur.com/snQjxhG.png

**Comment by Jason2605** [comment]
Which link did you click which sends you back? All the ones I've tried works perfectly for me. When did you download the panel?

**Comment by Finch-Tamo** [comment]
i've download your panel 8 hours ago i'm trying with the new sorry :s

**Comment by Finch-Tamo** [comment]
same problem 😢

**Comment by Jason2605** [comment]
Is there anyway you can give me access and ill take a look at what you have done, hop on discord or something if you can.
